#!/bin/bash
#
# The MIT License (MIT)
# Copyright (c) 2014 Julien Limoges
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

BASENAME=$(basename $0)

SILENT=false

usage()
{
    echo "usage:  $BASENAME file..."
    echo "        Simple program to read a file line by line, choosing to echo or not."
    echo "        Useful for executing commands one by one"
    return 0
}

display()
{
    echo "$@" 1>&2
}

passthrough()
{
    echo "$@"
}

err_msg()
{
    echo "$BASENAME: $@" 1>&2
    return 0
}

main()
{
    if [[ "$#" -lt 1 ]]; then
        err_msg "missing file operand"
        exit 1
    fi

    for file in $@; do
        display "for $file"
        while read -r -u3 line; do
            display -n "$line"
            read -s -r -N1 
            case "$REPLY" in
                $'\x0a')
                    echo "$line"
                ;;
            esac
            display ""
        done 3< <(cat $file)
    done

    return 0
}

# Emulate a program main to have better flow control throughout the program
main $@

